# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'podSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for podSample

  pod 'TestFrameWork' , :path => '../TestFrameWork'
  
  pod 'PodSwift' , :path => '../PodSwift'
  
  pod 'CircleMenu', :path => '../CircleMenu'
  
  pod 'MBProgressHUD'
  pod 'HWAutoScrollView'

  target 'podSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'podSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
